number of sites to be analyzed:  177
Traceback (most recent call last):
  File "Run.py", line 35, in <module>
    main(parser.parse_args())
  File "Run.py", line 16, in main
    test = ReCodonGeneconv( newicktree, alignment_file, paralog, Model = args.model, Force = Force, clock = args.clock, post_dup = args.post_dup)
  File "/home2/xji3/.local/lib/python2.7/site-packages/IGCexpansion/CodonGeneconv.py", line 85, in __init__
    self.initialize_parameters()
  File "/home2/xji3/.local/lib/python2.7/site-packages/IGCexpansion/CodonGeneconv.py", line 98, in initialize_parameters
    self.initialize_by_save(save_file)
  File "/home2/xji3/.local/lib/python2.7/site-packages/IGCexpansion/CodonGeneconv.py", line 1421, in initialize_by_save
    self.update_by_x()
  File "/home2/xji3/.local/lib/python2.7/site-packages/IGCexpansion/CodonGeneconv.py", line 270, in update_by_x
    self.unpack_x_process(Force_process = Force_process, transformation = transformation)
  File "/home2/xji3/.local/lib/python2.7/site-packages/IGCexpansion/CodonGeneconv.py", line 288, in unpack_x_process
    assert(len(self.x_process) == 6)
AssertionError
